
import javafx.beans.value.ChangeListener;
import javax.xml.bind.Marshaller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 1/20/2020
 *
 * @author Soheil Chapani
 */
public class EcuChecker extends javax.swing.JFrame {

    int n;
    private int rate;

    /**
     * Creates new form EcuChecker
     */
    public EcuChecker() {
        initComponents();
        txtResult.setEnabled(false);
        txtEngine.setEnabled(false);
        txtTires.setEnabled(false);
        txtElectric.setEnabled(false);
        txtHidrolics.setEnabled(false);
        txtOil.setEnabled(false);

        prElectric.setEnabled(false);
        prEngine.setEnabled(false);
        prTires.setEnabled(false);
        prHidrolics.setEnabled(false);
        prOil.setEnabled(false);

        btnStart.setEnabled(false);
        btnStop.setEnabled(false);

        value.setEnabled(false);

        chEngine.setEnabled(false);
        chElectric.setEnabled(false);
        chTires.setEnabled(false);
        chOil.setEnabled(false);
        chHidrolics.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResult = new javax.swing.JTextField();
        btnStart = new javax.swing.JToggleButton();
        btnStop = new javax.swing.JToggleButton();
        txtEngine = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTires = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtElectric = new javax.swing.JTextField();
        txtOil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHidrolics = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prEngine = new javax.swing.JProgressBar();
        prTires = new javax.swing.JProgressBar();
        prElectric = new javax.swing.JProgressBar();
        prOil = new javax.swing.JProgressBar();
        prHidrolics = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        value = new javax.swing.JSlider();
        chEngine = new javax.swing.JCheckBox();
        chTires = new javax.swing.JCheckBox();
        chElectric = new javax.swing.JCheckBox();
        chOil = new javax.swing.JCheckBox();
        chHidrolics = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 530));

        txtResult.setBackground(new java.awt.Color(51, 51, 51));
        txtResult.setFont(new java.awt.Font("DialogInput", 1, 10)); // NOI18N
        txtResult.setForeground(new java.awt.Color(51, 255, 51));
        txtResult.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtResult.setMaximumSize(new java.awt.Dimension(500, 500));

        btnStart.setBackground(new java.awt.Color(255, 255, 102));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 51, 255));
        btnStart.setText("start ");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(255, 255, 102));
        btnStop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnStop.setForeground(new java.awt.Color(255, 0, 51));
        btnStop.setText("stop ");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        txtEngine.setBackground(new java.awt.Color(204, 255, 204));
        txtEngine.setForeground(new java.awt.Color(0, 0, 255));
        txtEngine.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENGINE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIRES");

        txtTires.setBackground(new java.awt.Color(204, 255, 204));
        txtTires.setForeground(new java.awt.Color(0, 0, 255));
        txtTires.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ELECTRIC");

        txtElectric.setBackground(new java.awt.Color(204, 255, 204));
        txtElectric.setForeground(new java.awt.Color(0, 0, 255));
        txtElectric.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtOil.setBackground(new java.awt.Color(204, 255, 204));
        txtOil.setForeground(new java.awt.Color(0, 0, 255));
        txtOil.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("OIL TEMP");

        txtHidrolics.setBackground(new java.awt.Color(204, 255, 204));
        txtHidrolics.setForeground(new java.awt.Color(0, 0, 255));
        txtHidrolics.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HIDROLICS");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("ON");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 51));
        jButton2.setText("OFF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        value.setForeground(new java.awt.Color(51, 255, 255));

        chEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chEngineActionPerformed(evt);
            }
        });

        chTires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTiresActionPerformed(evt);
            }
        });

        chElectric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chElectricActionPerformed(evt);
            }
        });

        chOil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chOilActionPerformed(evt);
            }
        });

        chHidrolics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chHidrolicsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(jButton2))
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(chEngine)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prTires, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTires, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(chTires)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prElectric, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtElectric, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(chElectric)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prOil, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(chOil)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prHidrolics, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHidrolics, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(chHidrolics)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addGap(15, 15, 15)
                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(prEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chEngine)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(prTires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chTires)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(prElectric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chElectric)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtElectric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(prOil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chOil)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(prHidrolics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chHidrolics)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHidrolics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        txtResult.setEnabled(true);
        txtEngine.setEnabled(true);
        txtTires.setEnabled(true);
        txtElectric.setEnabled(true);
        txtHidrolics.setEnabled(true);
        txtOil.setEnabled(true);
        value.setEnabled(true);
        txtResult.setText("Checking the vehicle, please wait...");

        chEngine.setEnabled(true);
        chTires.setEnabled(true);
        chOil.setEnabled(true);
        chElectric.setEnabled(true);
        chHidrolics.setEnabled(true);

        

    }//GEN-LAST:event_btnStartActionPerformed
    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {
        rate = value.getValue();
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtResult.setText("Hello,ready to start...");
        txtEngine.setText("0");
        txtTires.setText("0");
        txtElectric.setText("0");
        txtHidrolics.setText("0");
        txtOil.setText("0");
        txtResult.setEnabled(true);
        txtEngine.setEnabled(true);
        txtTires.setEnabled(true);
        txtElectric.setEnabled(true);
        txtHidrolics.setEnabled(true);
        txtOil.setEnabled(true);

        value.setEnabled(true);

        prElectric.setEnabled(true);
        prEngine.setEnabled(true);
        prTires.setEnabled(true);
        prHidrolics.setEnabled(true);
        prOil.setEnabled(true);
        btnStart.setEnabled(true);
        btnStop.setEnabled(true);

        chEngine.setEnabled(true);
        chElectric.setEnabled(true);
        chTires.setEnabled(true);
        chOil.setEnabled(true);
        chHidrolics.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtResult.setEnabled(false);
        txtEngine.setEnabled(false);
        txtTires.setEnabled(false);
        txtElectric.setEnabled(false);
        txtHidrolics.setEnabled(false);
        txtOil.setEnabled(false);

        txtResult.setText("");
        txtEngine.setText("");
        txtTires.setText("");
        txtElectric.setText("");
        txtHidrolics.setText("");
        txtOil.setText("");

        value.setEnabled(false);

        prElectric.setEnabled(false);
        prEngine.setEnabled(false);
        prTires.setEnabled(false);
        prHidrolics.setEnabled(false);
        prOil.setEnabled(false);
        btnStart.setEnabled(false);
        btnStop.setEnabled(false);

        chEngine.setEnabled(false);
        chElectric.setEnabled(false);
        chTires.setEnabled(false);
        chOil.setEnabled(false);
        chHidrolics.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        txtResult.setText("Checking stopped...");
        value.setEnabled(false);

        chEngine.setSelected(false);
        chElectric.setSelected(false);
        chTires.setSelected(false);
        chHidrolics.setSelected(false);
        chOil.setSelected(false);

        chEngine.setEnabled(false);
        chTires.setEnabled(false);
        chElectric.setEnabled(false);
        chHidrolics.setEnabled(false);
        chOil.setEnabled(false);

        chEngine.setEnabled(false);
        chTires.setEnabled(false);
        chOil.setEnabled(false);
        chElectric.setEnabled(false);
        chHidrolics.setEnabled(false);


    }//GEN-LAST:event_btnStopActionPerformed

    private void chEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chEngineActionPerformed
        if (chEngine.isSelected()) {
            txtResult.setText("Checking the Engine...");
            chTires.setSelected(false);
            chElectric.setSelected(false);
            chHidrolics.setSelected(false);
            chOil.setSelected(false);

            chTires.setEnabled(false);
            chElectric.setEnabled(false);
            chHidrolics.setEnabled(false);
            chOil.setEnabled(false);

            txtElectric.setEnabled(false);
            txtTires.setEnabled(false);
            txtOil.setEnabled(false);
            txtHidrolics.setEnabled(false);

            prElectric.setEnabled(false);
            prTires.setEnabled(false);
            prOil.setEnabled(false);
            prHidrolics.setEnabled(false);

        } else {
            chTires.setEnabled(true);
            chElectric.setEnabled(true);
            chHidrolics.setEnabled(true);
            chOil.setEnabled(true);

            txtResult.setText("");

            txtElectric.setEnabled(true);
            txtTires.setEnabled(true);
            txtOil.setEnabled(true);
            txtHidrolics.setEnabled(true);

            prElectric.setEnabled(true);
            prTires.setEnabled(true);
            prOil.setEnabled(true);
            prHidrolics.setEnabled(true);
        }
    }//GEN-LAST:event_chEngineActionPerformed

    private void chTiresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTiresActionPerformed

        if (chTires.isSelected()) {
            txtResult.setText("Checking Tires...");
            chEngine.setSelected(false);
            chElectric.setSelected(false);
            chHidrolics.setSelected(false);
            chOil.setSelected(false);

            chEngine.setEnabled(false);
            chElectric.setEnabled(false);
            chHidrolics.setEnabled(false);
            chOil.setEnabled(false);

            prElectric.setEnabled(false);
            prEngine.setEnabled(false);
            prOil.setEnabled(false);
            prHidrolics.setEnabled(false);

        } else {
            chEngine.setEnabled(true);
            chElectric.setEnabled(true);
            chHidrolics.setEnabled(true);
            chOil.setEnabled(true);

            txtResult.setText("");

            prElectric.setEnabled(true);
            prEngine.setEnabled(true);
            prOil.setEnabled(true);
            prHidrolics.setEnabled(true);
        }


    }//GEN-LAST:event_chTiresActionPerformed

    private void chElectricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chElectricActionPerformed
        if (chElectric.isSelected()) {
            txtResult.setText("Checking Electric...");
            chTires.setSelected(false);
            chEngine.setSelected(false);
            chHidrolics.setSelected(false);
            chOil.setSelected(false);

            chTires.setEnabled(false);
            chEngine.setEnabled(false);
            chHidrolics.setEnabled(false);
            chOil.setEnabled(false);

            prEngine.setEnabled(false);
            prTires.setEnabled(false);
            prOil.setEnabled(false);
            prHidrolics.setEnabled(false);

        } else {
            chTires.setEnabled(true);
            chEngine.setEnabled(true);
            chHidrolics.setEnabled(true);
            chOil.setEnabled(true);

            txtResult.setText("");

            prEngine.setEnabled(true);
            prTires.setEnabled(true);
            prOil.setEnabled(true);
            prHidrolics.setEnabled(true);

        }
    }//GEN-LAST:event_chElectricActionPerformed

    private void chOilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chOilActionPerformed
        if (chOil.isSelected()) {
            txtResult.setText("Checking Oil Temp...");
            chTires.setSelected(false);
            chElectric.setSelected(false);
            chHidrolics.setSelected(false);
            chEngine.setSelected(false);

            chTires.setEnabled(false);
            chElectric.setEnabled(false);
            chHidrolics.setEnabled(false);
            chEngine.setEnabled(false);

            prEngine.setEnabled(false);
            prTires.setEnabled(false);
            prElectric.setEnabled(false);
            prHidrolics.setEnabled(false);

        } else {
            chTires.setEnabled(true);
            chElectric.setEnabled(true);
            chHidrolics.setEnabled(true);
            chEngine.setEnabled(true);

            txtResult.setText("");

            prEngine.setEnabled(true);
            prTires.setEnabled(true);
            prElectric.setEnabled(true);
            prHidrolics.setEnabled(true);

        }
    }//GEN-LAST:event_chOilActionPerformed

    private void chHidrolicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chHidrolicsActionPerformed
        if (chHidrolics.isSelected()) {
            txtResult.setText("Checking Hidrolics...");
            chTires.setSelected(false);
            chElectric.setSelected(false);
            chEngine.setSelected(false);
            chOil.setSelected(false);

            chTires.setEnabled(false);
            chElectric.setEnabled(false);
            chEngine.setEnabled(false);
            chOil.setEnabled(false);

            prEngine.setEnabled(false);
            prTires.setEnabled(false);
            prElectric.setEnabled(false);
            prOil.setEnabled(false);

        } else {
            chTires.setEnabled(true);
            chElectric.setEnabled(true);
            chEngine.setEnabled(true);
            chOil.setEnabled(true);

            txtResult.setText("");

            prEngine.setEnabled(true);
            prTires.setEnabled(true);
            prElectric.setEnabled(true);
            prOil.setEnabled(true);
        }
    }//GEN-LAST:event_chHidrolicsActionPerformed
    public void checkValue() {
        if (chEngine.isSelected()) {
            txtEngine.setText(value.getValue()+"");

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcuChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcuChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcuChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcuChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcuChecker().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnStart;
    private javax.swing.JToggleButton btnStop;
    private javax.swing.JCheckBox chElectric;
    private javax.swing.JCheckBox chEngine;
    private javax.swing.JCheckBox chHidrolics;
    private javax.swing.JCheckBox chOil;
    private javax.swing.JCheckBox chTires;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar prElectric;
    private javax.swing.JProgressBar prEngine;
    private javax.swing.JProgressBar prHidrolics;
    private javax.swing.JProgressBar prOil;
    private javax.swing.JProgressBar prTires;
    private javax.swing.JTextField txtElectric;
    private javax.swing.JTextField txtEngine;
    private javax.swing.JTextField txtHidrolics;
    private javax.swing.JTextField txtOil;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtTires;
    private javax.swing.JSlider value;
    // End of variables declaration//GEN-END:variables
}
